[package]
name = "mem-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
okm-core.workspace = true
okm-derive.workspace = true
fjall.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
knus = "3.4.0"
miette = "7.6.0"

[dev-dependencies]
tempfile.workspace = true
